# Generated by Django 4.1.4 on 2023-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_title', models.CharField(max_length=250)),
                ('bookmark_address', models.CharField(max_length=1000)),
                ('bookmark_notes', models.CharField(max_length=100000, null=True)),
                ('bookmark_save_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
