# Generated by Django 4.1.4 on 2023-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks_main', '0002_saved_bookmarks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_bookmarks',
            name='bookmark_title',
            field=models.TextField(max_length=250),
        ),
    ]
