# Generated by Django 4.1.4 on 2023-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks_main', '0003_alter_saved_bookmarks_bookmark_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_bookmarks',
            name='bookmark_title',
            field=models.CharField(max_length=250),
        ),
    ]
